name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'mikhaillav'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
            review-message: "Auto approved automated Pull request"
            github-token: ${{ secrets.USER_TOKEN }}
